Bugfixes and syntax improvements
AccesoGroup/api_sdk pull request #1
Opened 2018-02-09 14:42 UTC by franramirez688

General refactor in `bwproject.py`

2018-02-12 10:33 UTC, champ requested changes
@franramirez688  Reviewed

2018-02-12 10:33 UTC, champ commented on bwdata.py
>          params["pageSize"] = kwargs["pageSize"] if "pageSize" in kwargs else 5000
Let’s use `page_size` as `kwarg` for consistency, and use `get()` to retrieve its value and default value if not present.

2018-02-12 10:33 UTC, champ commented on bwdata.py
> +        return self.project.get(endpoint="data/" + y_axis + "/" + x_axis + "/" + breakdown_by,
Change to use format to compose endpoint string

2018-02-12 10:33 UTC, champ commented on bwdata.py
>          filled["endDate"] = data["endDate"] if "endDate" in data else (
Change to `end_date` in `data` for consistency. Use `get()` to get value or default value.

2018-02-12 10:33 UTC, champ commented on bwproject.py
> +    def _update_by_test_auth(self, username, token):
Add docstring

2018-02-19 11:00 UTC, franramirez688 reviewed
@champ review again

2018-02-19 11:01 UTC, franramirez688 commented on bwproject.py
> +    def _update_by_test_auth(self, username, token):
It was already added

2018-02-19 15:34 UTC, merged